# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Countries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Countries
  pod 'ReachabilitySwift'

  target 'CountriesTests' do
    inherit! :search_paths
    
  end

  target 'CountriesUITests' do
    inherit! :search_paths
    
  end

end
